id: ID7970F49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:36:29+00:00'
last_modified: '2022-06-07T12:42:39.959188+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21968
  title: བོད་ཀྱི་ལོ་རྒྱུས་སྤྱི་དོན་པདྨ་རཱ་གའི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    9C5C:
      image_group_id: I5805
      title: ''
      total_pages: 540
      order: 1
      base_file: 9C5C.txt
    8AEE:
      image_group_id: I5806
      title: ''
      total_pages: 592
      order: 2
      base_file: 8AEE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
